#include <stdint.h>
#include <limero/codec.h>
#include <limero/msg.h>

typedef enum HbVar {
    CTRL_MOD = 0,
    CTRL_TYP,
    CUR_MOT_MAX,
    RPM_MOT_MAX,
    FI_WEAK_ENA,
    FI_WEAK_HI,
    FI_WEAK_LO,
    FI_WEAK_MAX,
    PHASE_ADV_MAX_DEG,
    IN1_RAW,
    IN1_TYP,
    IN1_MIN,
    IN1_MID,
    IN1_MAX,
    IN1_CMD,
    IN2_RAW,
    IN2_TYP,
    IN2_MIN,
    IN2_MID,
    IN2_MAX,
    IN2_CMD,
    AUX_IN1_RAW,
    AUX_IN1_TYP,
    AUX_IN1_MIN,
    AUX_IN1_MID,
    AUX_IN1_MAX,
    AUX_IN1_CMD,
    AUX_IN2_RAW,
    AUX_IN2_TYP,
    AUX_IN2_MIN,
    AUX_IN2_MID,
    AUX_IN2_MAX,
    AUX_IN2_CMD,
    DC_CURR,
    RDC_CURR,
    LDC_CURR,
    CMDL,
    CMDR,
    SPD_AVG,
    SPDL,
    SPDR,
    FILTER_RATE,
    SPD_COEF,
    STR_COEF,
    BATV,
    TEMP,
} HbVar;

